version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install -r "requirements.txt" 
      - sudo apt-get install gunicorn
  post_build:
    commands:
      - gunicorn -w 4 --reload --bind 127.0.0.1:5000 wsgi:app_instance